### ISSUE TITLE
Dart2JS build fails

### ISSUE THREAD

**Issue by CarrKnight** [MichaelFenwick/Color#10]
Whenever I try to ```pub build demo``` dart2js fails with the following:

    package:color/color.dart: 'case' expression type 'TypeImpl' overrides 'operator =='.

This is in spite of the fact that the package works very well in dartium

**Comment by MichaelFenwick** [comment]
Seems I was using the switch statement in a way that wasn't allowed by Dart. It shouldn't have run in Dartium at all. I've changed the switch to an if/else if/else so it should all be good now.

**Comment by ciasaboark** [comment]
Thanks for the fix.  Can the 2.0.1 build be pushed to pub.dartlang.org?
