### ISSUE TITLE
strong mode compliancy

### ISSUE THREAD

**Issue by sircco** [MichaelFenwick/Color#12]
Hello
I was trying to compile your code with dartdevc and some problems arrised that are preventing our code to compile.

one of errors..
_[error] The argument type '(CielabColor, [List<dynamic>]) → CielabColor' can't be assigned to the parameter type 'FilterFunction(Color, [List<dynamic>]) → Color'. (package:color/color_filter.dart, line 25, col 4_

i know this is supposed to be extendable with your current implementation but maybe you can offer different api  with named arguments. This would  solve static typing problem.
ex: 
```
  static ColorFilter lighten = new ColorFilter((CielabColor color, {num percent:0.1})
    return new CielabColor(color.l * (1 + percent), color.a, color.b);
  }, CielabColor);
```

**Comment by MichaelFenwick** [comment]
Closing this as since Dart 2.0, the package has been strong mode compliant.
