### ISSUE TITLE
Error when using dart2js trust types & primitives

### ISSUE THREAD

**Issue by jimmyff** [MichaelFenwick/Color#15]
If I run dart2js with `commandLineOptions: ['--trust-type-annotations', '--trust-primitives']` 

I get the following error:

```
Uncaught Error: NoSuchMethodError: method not found: 'toHslColor$0' (color.toHslColor$0 is not a function)
```

**Comment by MichaelFenwick** [comment]
Closing as this does not occur any longer when using the latest version of the package.
