### ISSUE TITLE
Publish 2.1.0 to support Dart 2.0

### ISSUE THREAD

**Issue by bkonyi** [MichaelFenwick/Color#21]
It looks like you've updated the SDK constraints to allow for version 2.1.0 to be used with Dart 2.0. Would you mind publishing a new version with the updated constraints to Pub? Otherwise it's not possible to use for those on the latest Dart revision.

**Comment by bkonyi** [comment]
Friendly bump. Can the latest version be published on pub?

**Comment by MichaelFenwick** [comment]
Should be published now. Let me know if there are any problems with it.
