### ISSUE TITLE
Importing blocks access to Color.lerp

### ISSUE THREAD

**Issue by TonyMilton** [MichaelFenwick/Color#22]
Color.lerp is static and it blocked when importing:

import 'package:color/color.dart';

I have tried to import just what I need, e.g:
import 'package:color/hex_color.dart';

But IntelliJ IDEA says it imported library can't have a part of directive

**Comment by MichaelFenwick** [comment]
You can import a subset of a library by using the `show` keyword, as in `import 'package:color/color.dart' show HslColor;`
